### ISSUE TITLE
是否能增加以下功能

### ISSUE THREAD

**Issue by sioisan** [chilbi/KasumiNotes#1]
看到最近增加了深域地图信息，不知作者是否有兴趣增加以下功能

1. ## 环境效果
- 环境效果位于表**extra_effect_data**，通过**target_value_1**关联（目前只用了target_value_1）。
会战是boss的**enemy_id**，其它副本是**wave_group_id**。
查询出enemy_id_1~5，再去副本对应的XXX_enemy_parameter表查询出对应的单位。

2. ## 技能TP减少
- 技能TP减少数值在技能的伤害动作中的**action_detail_3**，为百分比数值。
  > 比如100就是不会获得TP，80就是获得20%TP

3. ## 其它副本
以下副本基础结构基本和深域一样，只是表不一样
 - 深渊讨伐战
>排期：abyss_schedule
>关卡信息：abyss_quest_data
>关卡阵容：abyss_wave_group_data
>敌人信息：abyss_enemy_parameter

 - 追忆战
>关卡信息：追忆战·霸：mirage_nemesis_quest、追忆战：mirage_floor_quest
> 关卡阵容：mirage_wave_group_data
> 敌人信息：mirage_enemy_parameter

**Comment by chilbi** [comment]
@sioisan 增加了环境效果和技能TP减少，深渊讨伐战和追忆战也增加了
